contracts:
  config:
    rentCarContract:
      contract-id: A1oNQZFwmqRekTiUej7fpyyxm95gCrUAinGPe5BUzJpw
      image: registry.web3tech.ru/icore-sc/rent-car-contract-test:1.0.1
      imageHash: a7e5b21f2f1fc5032650eaaa3a2b2e2490720bcce352f4cc08ebf08c33d09791
      version: 3
      fee: 0
      validation-enabled: false
      auto-update:
        enabled: false
        contractCreatorAddress: 3MQ3RhgAXcX7rTJYWa7iBcpwwwHYF769u33
    blackListContract:
      contract-id: B7rk3WzZMom78YXNM1WSmVSpqTTqkWPaQNorCNFoixvY
      image: registry.web3tech.ru/icore-sc/black-list-contract-test:1.0.5
      imageHash: 99cc84f9f500755f5cd9690ee862b4cb88d7f1f3c7d4c6e0c39f69a995702497
      version: 3
      fee: 0
      auto-update:
        enabled: false
        contractCreatorAddress: 3MQ3RhgAXcX7rTJYWa7iBcpwwwHYF769u33

node:
  credentials-provider:
    addresses:
      3MQ3RhgAXcX7rTJYWa7iBcpwwwHYF769u33: dP0Lm9hEnmVCr44A

  config:
    node-0:
      http:
        xApiKey: udYk81TCtagSwUwg
        xPrivacyApiKey: udYk81TCtagSwUwg
        url: https://node
        loggerLevel: FULL
        read-timeout: 30000

rent-car:
  db-schema: rent_car

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${rent-car.db-schema}
        event:
          merge:
            entity_copy_observer: allow
        jdbc:
          time_zone: UTC
          log.warnings: true
          lob.non_contextual_creation: true
    show-sql: false
  application:
    name: rent-car-app
  datasource:
    hikari:
      schema: ${rent-car.db-schema}
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: rent-car-app-jpa-pool
      max-lifetime: 100000
      connection-timeout: 30000
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/rent_car
    username: postgres
    password: postgres
  flyway:
    enabled: true
    schemas: ${rent-car.db-schema}
    default-schema: ${rent-car.db-schema}

tx-observer:
  activation-height: 3750000
  queue-cleaner:
    enabled: true
  privacy-check:
    enabled: true

logging:
  level:
    com:
      wavesenterprise:
        sdk:
          node:
            client:
              blocking:
                tx:
                  TxService:
                    DEBUG

server:
  port: 8081
